Resources:
  MealsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-MealsQueue
      VisibilityTimeout: 130
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        maxReceiveCount: 2
        deadLetterTargetArn: !GetAtt MealsDLQ.Arn

  MealsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-MealsDLQ
      MessageRetentionPeriod: 1209600 # 14 days

  MealsDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ${self:service}-${self:provider.stage}-MealsDLQAlarm
      AlarmDescription: Triggered when messages are found in MealsDLQ
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt MealsDLQ.QueueName
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref DLQAlarmsTopic