Resources:
  APIGWCustomDomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: ${env:API_DOMAIN_NAME}
      ValidationMethod: DNS  
      DomainValidationOptions:
        - DomainName: ${env:API_DOMAIN_NAME}
          HostedZoneId: ${env:ROUTE53_HOSTED_ZONE_ID}

