Resources:
  DLQAlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:service}-${self:provider.stage}-DLQAlarmsTopic
      Subscription:
        - Protocol: email
          Endpoint: ${env:DLQ_ALARM_EMAIL}
          