Conditions:
  ShouldSetupMealsCDNCustomDomain: !And
    - !Not
      - !Equals
        - ${env:MEALS_CDN_DOMAIN_NAME, ''}
        - ''
    - !Not
      - !Equals
        - ${env:MEALS_CDN_CERTIFICATE_ARN, ''}
        - ''
    - !Not
      - !Equals
        - ${env:ROUTE53_HOSTED_ZONE_ID, ''}
        - ''

Resources:
  MealsCDNOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: ${self:service}-${self:provider.stage}-MealsCDNOAC
        Description: OAC for NourishBucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  MealsBucketCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2and3
        Aliases: !If
          - ShouldSetupMealsCDNCustomDomain
          -
            - ${env:MEALS_CDN_DOMAIN_NAME, ''}
          - !Ref AWS::NoValue
        ViewerCertificate: !If
          - ShouldSetupMealsCDNCustomDomain
          -
            AcmCertificateArn: ${env:MEALS_CDN_CERTIFICATE_ARN, ''}
            MinimumProtocolVersion: TLSv1.2_2021
            SslSupportMethod: sni-only
          -
            CloudFrontDefaultCertificate: true

        Origins:
          - Id: S3Origin
            S3OriginConfig: {}
            DomainName: !GetAtt NourishBucket.RegionalDomainName
            OriginAccessControlId: !Ref MealsCDNOAC
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#managed-cache-caching-optimized
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6

  MealsBucketCDNPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref NourishBucket
      PolicyDocument:
        Version: '2008-10-17'
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${NourishBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${MealsBucketCDN}'

  MealsCDNCustomDomainDNSRecord:
    Condition: ShouldSetupMealsCDNCustomDomain
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: ${env:ROUTE53_HOSTED_ZONE_ID, ''}
      Type: A
      Name: ${env:MEALS_CDN_DOMAIN_NAME, ''}
      AliasTarget:
        # https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/TemplateReference/aws-properties-route53-recordset-aliastarget.html#cfn-route53-recordset-aliastarget-hostedzoneid
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt MealsBucketCDN.DomainName           
